load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "executor",
    srcs = ["executor.go"],
    importpath = "github.com/bryantinsley/machinator/backend/internal/executor",
    visibility = ["//backend:__subpackages__"],
)
