load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "styles",
    srcs = ["styles.go"],
    importpath = "github.com/bryantinsley/machinator/orchestrator/pkg/ui/styles",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_charmbracelet_lipgloss//:lipgloss",
    ],
)
