# Templates used by the machinator orchestrator

filegroup(
    name = "templates",
    srcs = [
        "directive_template.txt",
        "setup_go_env.sh",
        "unblocking_directive.txt",
    ],
    visibility = ["//visibility:public"],
)

exports_files([
    "directive_template.txt",
    "unblocking_directive.txt",
    "setup_go_env.sh",
])
